name: Generate static translations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dryRun:
    runs-on: ubuntu-latest
    steps:
      # v4
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      # We always run dry-run the script to verify that it still works.
      # The generateTranslations script runs with ts-node, which can't handle Flow
      # (the specialized JS that React Native is written in).
      # Therefore, adding an import in the wrong place could break the script, even if you didn't modify the script.
      - name: Run full generateTranslations dry run
        run: npx ts-node ./scripts/generateTranslations.ts --dry-run

      - name: Explain failure
        if: failure()
        run: |
          echo '::error:: 😦 Something you did broke scripts/generateTranslations.ts. Most likely, this means you added an import that caused react-native to be directly or indirectly imported into the script.'
          exit 1

      - name: Run generateTranslations for added translations
        run: npx ts-node ./scripts/generateTranslations.ts --compare-ref=main

      - name: Post diff in PR as a comment
        run: |
          # Check if there are any changes after running generateTranslations
          if git diff --quiet HEAD; then
            echo "✅ No changes detected"
          else
            echo "🦜 Polyglot Parrot detected changes! 🦜"
            COMMENT_BODY="## 🦜 Polyglot Parrot! 🦜

            Squawk! Looks like you added some shiny new English strings. Allow me to parrot them back to you in other tongues:

            \`\`\`diff
            $(git diff HEAD)
            \`\`\`

            _Note:_ You can apply these changes by copying them to your clipboard, then running \`pbpaste | git apply\`"
            gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
